"""Add description to House

Revision ID: a701ebaf5c1e
Revises: 
Create Date: 2024-10-28 15:19:44.992426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a701ebaf5c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('house_type')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('listed_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listed_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('house_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
